"""``knowitall2 update``: bring KnowItAll2 up to date the way it was installed, in one step.

Installed by giving a coding agent the repository address, KnowItAll2 is
updated by telling the agent "update KnowItAll2": the agent runs the update
script that setup writes into the data home (``update.py``), which runs this.

1. Download: ``git pull --ff-only`` in the KnowItAll2 clone. Local changes or
   a history that moved (not a fast-forward) stop the update, unchanged.
2. Finish with the new version's own code, in a fresh process:
   - refresh each agent that was set up, changing only what is out of date;
   - when Codex is running, change nothing in Codex's own settings or hook
     (they could be overwritten, and a changed hook needs trusting again);
     its KnowItAll2 instructions, which KnowItAll2 owns, are still refreshed;
   - refresh the app's shortcut and this update script;
   - run the health checks and say, in plain words, what changed and what
     the user needs to do.
"""

from __future__ import annotations

import os
import re
import shlex
import subprocess
import sys
from pathlib import Path

from . import __version__, journal
from .files import write_text_atomic
from .paths import HOME_ENVIRONMENT_VARIABLE, data_home

LAUNCHER = "update.py"
VERSION_FILE = "installed-version"
UPDATE_LOCK = "update-run.lock"
_VERSION = re.compile(r'__version__ = "([^"]+)"')
# Set while the update script runs itself again with the Python KnowItAll2 was set up with.
_RELAUNCHED = "KNOWITALL2_UPDATE_RELAUNCHED"
# What to do after the update added or changed Codex's KnowItAll2 hooks.
TRUST_HOOKS = "In Codex, type /hooks and trust the KnowItAll2 hooks it shows as new or changed."


def checkout_root() -> Path | None:
    """The Git clone this KnowItAll2 runs from, if it runs from one."""

    root = Path(__file__).resolve().parents[2]
    return root if (root / "pyproject.toml").is_file() and (root / ".git").exists() else None


def launcher_path() -> Path:
    return data_home() / LAUNCHER


def render_launcher() -> str:
    """The update script. It runs the update with the Python KnowItAll2 was set up with, whichever starts it.

    Agents start the MCP server and the hooks with that Python, and the update
    sets them up again with the Python it runs with: under another one (a
    ``python`` that is conda's, or another version) it would move every agent
    to it, and a changed Codex hook needs trusting again.
    """

    from .agents.base import server_launch

    launch = server_launch()
    lines = ['"""Generated by KnowItAll2 setup: updates KnowItAll2. Run it with Python 3.12 or later."""',
             "import os", "import subprocess", "import sys", "",
             "# The Python KnowItAll2 was set up with, which the agents run it with.",
             f"SETUP_PYTHON = {launch.command!r}",
             f"RELAUNCHED = os.environ.pop({_RELAUNCHED!r}, '')",
             "RUNNING = os.path.normcase(os.path.abspath(sys.executable))",
             "if not RELAUNCHED and RUNNING != os.path.normcase(SETUP_PYTHON):",
             "    if os.path.isfile(SETUP_PYTHON):",
             "        print('Running the update with ' + SETUP_PYTHON + ', the Python KnowItAll2 was set up with.', "
             "flush=True)",
             f"        environment = dict(os.environ, {_RELAUNCHED}='1')",
             "        raise SystemExit(subprocess.run([SETUP_PYTHON, os.path.abspath(__file__), *sys.argv[1:]], "
             "env=environment).returncode)",
             "    print('The Python KnowItAll2 was set up with (' + SETUP_PYTHON + ') is no longer there, so this "
             "update uses ' + sys.executable + ' and sets up the agents with it.', flush=True)",
             ""]
    if "PYTHONPATH" in launch.env:
        lines.append(f"sys.path.insert(0, {launch.env['PYTHONPATH']!r})")
    if HOME_ENVIRONMENT_VARIABLE in launch.env:
        lines.append(f"os.environ.setdefault({HOME_ENVIRONMENT_VARIABLE!r}, {launch.env[HOME_ENVIRONMENT_VARIABLE]!r})")
    lines += ["from knowitall2.cli import main", "", 'raise SystemExit(main(["update"]))', ""]
    return "\n".join(lines)


def write_launcher() -> bool:
    """Write the update script into the data home; True if it changed."""

    text = render_launcher()
    path = launcher_path()
    try:
        if path.read_text(encoding="utf-8") == text:
            return False
    except OSError:
        pass
    write_text_atomic(path, text)
    return True


def update_command() -> str:
    """How a person runs the update in a terminal on this computer (PowerShell on Windows), with its own Python."""

    from .agents.base import console_python

    if sys.platform == "win32":
        return f'& "{console_python()}" "{launcher_path()}"'
    return f"{shlex.quote(console_python())} {shlex.quote(str(launcher_path()))}"


def run(*, runner=subprocess.run) -> int:
    """Download the new version, then finish with its code; one update at a time on this computer."""

    from .learning.state import LockBusy, RunLock

    try:
        with RunLock(data_home() / UPDATE_LOCK):
            return _run(runner)
    except LockBusy:
        print("Another KnowItAll2 update is running on this computer; let it finish. Nothing was changed.")
        return 1


def _run(runner) -> int:
    root = checkout_root()
    if root is None:
        print("This copy of KnowItAll2 was not installed from a Git clone, so it cannot update itself. "
              "Install it again by following docs/install-for-agents.md.")
        return 1
    environment = dict(os.environ, GIT_TERMINAL_PROMPT="0")

    def git(*arguments: str) -> subprocess.CompletedProcess:
        return runner(["git", "-C", str(root), *arguments], capture_output=True, text=True, timeout=180,
                      env=environment)

    try:
        dirty = git("status", "--porcelain", "--untracked-files=no")
        if dirty.returncode != 0:
            print(f"KnowItAll2 could not check its folder {root}: {_last(dirty.stderr)}")
            return 1
        if dirty.stdout.strip():
            print(f"KnowItAll2 was not updated: its folder {root} has local changes. Nothing was changed.")
            return 1
        before = git("rev-parse", "HEAD").stdout.strip()
        pulled = git("pull", "--ff-only")
    except (OSError, subprocess.SubprocessError) as exc:
        print(f"KnowItAll2 could not run Git to download the update: {exc}")
        return 1
    if pulled.returncode != 0:
        detail = _last(pulled.stderr) or _last(pulled.stdout)
        if "authentication" in detail.casefold() or "could not read username" in detail.casefold():
            detail += " (Git could not sign in to the repository; sign in with your usual Git tool, then try again.)"
        print(f"KnowItAll2 could not download the update: {detail}\nNothing was changed.")
        journal.problem("update", f"git pull failed: {detail}")
        return 1
    after = git("rev-parse", "HEAD").stdout.strip()
    # Finish with the new code, not the code of this already-running process.
    finish = [sys.executable, "-B", "-P", "-m", "knowitall2", "update", "--finish", "--previous", __version__]
    if before == after:
        finish.append("--unchanged")
    environment["PYTHONPATH"] = str(root / "src") + (os.pathsep + environment["PYTHONPATH"]
                                                     if environment.get("PYTHONPATH") else "")
    if before != after:
        # The new code must at least start before every agent is pointed at it; otherwise go back at once
        # (the folder had no changes of its own, so nothing of the user's is lost).
        try:
            started = runner([sys.executable, "-B", "-P", "-m", "knowitall2", "--version"], capture_output=True,
                             text=True, timeout=120, env=environment)
            failed = started.returncode != 0
            detail = _last(started.stderr) or _last(started.stdout)
        except (OSError, subprocess.SubprocessError) as exc:
            failed, detail = True, str(exc)
        if failed:
            git("reset", "--hard", before)
            print(f"KnowItAll2 downloaded a new version that does not start ({detail}), so it went back to the "
                  "version you had. Nothing else was changed.")
            journal.problem("update", f"the new version did not start, so the update was undone: {detail}")
            return 1
    environment.pop("GIT_TERMINAL_PROMPT", None)
    code = runner(finish, env=environment).returncode
    if code != 0 and before != after:
        print(f"The update did not finish. To go back to the version you had, run: git -C \"{root}\" reset "
              f"--hard {before}")
    return code


def finish(*, previous: str, unchanged: bool, codex_running=None) -> int:
    """Refresh every agent and the app after a download, and report in plain words."""

    from .agents import AGENT_NAMES, AgentError, adapter_for, server_launch
    from .agents import instructions
    from .agents.base import install_skill, was_set_up
    from .agents.codex import hooks_unavailable
    from .app import shortcut
    from .doctor import run_checks

    running = codex_running if codex_running is not None else is_codex_running
    # The version last set up on this computer tells what is new, even when the
    # download happened before this ran (the first update from a version without it).
    seen = seen_version()
    if seen is not None and seen != __version__:
        previous, unchanged = seen, False
    elif seen is None and previous == __version__:
        previous, unchanged = None, False
    if unchanged:
        first = f"KnowItAll2 is up to date ({__version__})."
    elif previous is None:
        first = f"KnowItAll2 is now version {__version__}."
    else:
        first = f"KnowItAll2 was updated from {previous} to {__version__}."
    lines = [first]
    todo: list[str] = []
    launch = server_launch()
    for name in AGENT_NAMES:
        adapter = adapter_for(name)
        if not was_set_up(adapter):
            continue
        # The hook launcher is KnowItAll2's own file and the agent's hook command does not change
        # with it: refresh it even while the agent is open, and with nothing to trust again.
        try:
            refreshed = adapter.refresh_hook_launcher(launch)
        except OSError as exc:
            refreshed = None
            journal.problem("update", f"the {adapter.display_name} hook launcher could not be refreshed: {exc}")
        outdated = [check for check in adapter.checks(launch) if not check.ok]
        if not outdated:
            lines.append(f"- {adapter.display_name}: {f'updated ({refreshed})' if refreshed else 'already up to date'}.")
            continue
        # The Skill and the instructions block are KnowItAll2's own text, which agents only read.
        settings_outdated = [check for check in outdated
                             if "Skill" not in check.name and "instructions" not in check.name]
        try:
            if name == "codex" and running():
                # Setup may rewrite Codex's config.toml even when only the Skill is out of
                # date, and an open Codex can overwrite it: refresh only what KnowItAll2 owns.
                changed = install_skill(adapter.skills_dir)
                changed = instructions.install(adapter.instructions_path) or changed
                if settings_outdated:
                    lines.append(f"- Codex: {'its KnowItAll2 instructions were updated; ' if changed else ''}"
                                 "its settings need a change that cannot be made while Codex is open.")
                    todo.append(f"Close Codex, then run the update again (in another agent, or in a terminal: "
                                f"{update_command()}).")
                else:
                    lines.append("- Codex: its KnowItAll2 instructions were updated.")
                continue
            changes = [*([refreshed] if refreshed else []), *adapter.setup(launch)]
        except (AgentError, OSError) as exc:
            lines.append(f"- {adapter.display_name}: could not be updated: {exc}")
            continue
        lines.append(f"- {adapter.display_name}: updated ({'; '.join(changes) if changes else 'nothing to change'}).")
        # Where no Windows command can run the hooks, setup left them out and its change says why: nothing to trust.
        if (name == "codex" and any("hook" in check.name.lower() for check in settings_outdated)
                and not hooks_unavailable(launch)):
            todo.append(TRUST_HOOKS)
        if name == "claude-code" and settings_outdated:
            todo.append("Quit and reopen Claude Code so it keeps the new settings.")
    try:
        for change in shortcut.install():
            lines.append(f"- The app: {change}.")
        write_launcher()
    except Exception as exc:
        lines.append(f"- The app's shortcut could not be refreshed: {exc}")
    if not unchanged:
        try:
            from .learning.command import adopt_current_model

            moved = adopt_current_model()
        except Exception as exc:
            moved = None
            journal.problem("update", f"the learning model could not be updated: {exc}")
        if moved:
            lines.append(f"- Learning: now uses {moved}, which learns more, and more accurately. You can choose "
                         "another model in the app, under Learning.")
        try:
            from .learning import catchup
            from .paths import database_path
            from .store import Store

            store = Store.open(database_path())
            try:
                repaired = catchup.repair_once(store)
            finally:
                store.close()
        except Exception as exc:
            repaired = 0
            from .learning.state import LockBusy

            if not isinstance(exc, LockBusy):  # a learning run holds the lock: checked at the next update
                journal.problem("update", f"skipped past sessions could not be checked: {exc}")
        if repaired:
            lines.append(f"- Learning: {repaired} past sessions that were never learned are listed again under "
                         "catching up.")
    failing = [check for check in run_checks() if not check.ok]
    if failing:
        lines.append("Health check: " + "; ".join(f"{check.name}: {check.detail}" for check in failing))
    else:
        lines.append("Health check: everything is working.")
    if not unchanged:
        notes = changelog_since(previous)
        if notes:
            lines.append("What's new:")
            lines.extend(f"  {note}" for note in notes)
        todo.append(open_chats_advice(previous))
    if todo:
        lines.append("What to do now:")
        lines.extend(f"  {number}. {item}" for number, item in enumerate(todo, 1))
    print("\n".join(lines))
    remember_version()
    if not unchanged:
        journal.record_standalone("settings", first.removesuffix("."), outcome="updated", agent="update")
    return 0


def seen_version() -> str | None:
    try:
        return (data_home() / VERSION_FILE).read_text(encoding="utf-8").strip() or None
    except OSError:
        return None


def remember_version() -> None:
    """Note the version set up on this computer, for the next update's "what's new"."""

    try:
        write_text_atomic(data_home() / VERSION_FILE, __version__ + "\n")
    except OSError:
        pass


def changelog_since(previous: str | None, *, limit: int = 12) -> list[str]:
    """The headline of each change in the versions after ``previous`` (None: this version only)."""

    root = checkout_root() or Path(__file__).resolve().parents[2]
    try:
        text = (root / "CHANGELOG.md").read_text(encoding="utf-8")
    except OSError:
        return []
    notes: list[str] = []
    for match in re.finditer(r"^## (\S+) \(.*?\)\n(.*?)(?=^## |\Z)", text, re.MULTILINE | re.DOTALL):
        if previous is None and match.group(1) != __version__:
            continue
        if previous is not None and _version_key(match.group(1)) <= _version_key(previous):
            continue
        for bold in re.findall(r"^- \*\*(.+?)\*\*", match.group(2), re.MULTILINE):
            notes.append(f"{match.group(1)}: {bold.rstrip('.')}")
    return notes[:limit]


def is_codex_running() -> bool:
    """Whether a Codex app or command-line session is open on this computer."""

    try:
        if sys.platform == "win32":
            listed = subprocess.run(["tasklist", "/FI", "IMAGENAME eq codex.exe", "/NH"], capture_output=True,
                                    text=True, timeout=30, creationflags=subprocess.CREATE_NO_WINDOW)
            return "codex.exe" in listed.stdout.casefold()
        return subprocess.run(["pgrep", "-x", "codex"], capture_output=True, timeout=30).returncode == 0
    except (OSError, subprocess.SubprocessError):
        return True  # When unsure, assume it is open and leave its settings alone.


# The first version whose MCP server is the front, which runs the installed code for every request.
FRONT_SINCE = "0.4.0"


def open_chats_advice(previous: str | None) -> str:
    """What an update means for chats that are already open."""

    if previous is None or _version_key(previous) < _version_key(FRONT_SINCE):
        return ("Quit and reopen Claude Code and Codex once, so chats that are open now use the new version. "
                "After that, updates reach open chats by themselves.")
    return ("Chats that are open use the new version from their next KnowItAll2 request; new KnowItAll2 tools "
            "appear in open Codex chats after Codex restarts.")


def _version_key(version: str) -> tuple[int, ...]:
    return tuple(int(part) if part.isdigit() else 0 for part in version.split("."))


def _last(text: str) -> str:
    lines = [line.strip() for line in (text or "").splitlines() if line.strip()]
    return lines[-1][:300] if lines else ""
