"""The app's shortcut: installed with KnowItAll2, in the Start menu on Windows and the applications menu on Linux.

``knowitall2 setup`` calls :func:`install`. The shortcut runs a small launcher
kept in the data home, the way the agent hooks do, so it keeps working when
KnowItAll2 is updated in place.

On Windows, a program running inside a packaged desktop app (such as the
Claude desktop app, where a coding agent usually runs setup) cannot add to
the Start menu: Windows hides the file in that app's private storage. Setup
then puts the shortcut on the desktop, and the app adds itself to the Start
menu the first time it is opened from there, because Explorer starts it
outside any package.

What was made is remembered in ``app-shortcuts.json`` in the data home, so a
shortcut the user deleted, or removed with ``--remove-shortcut``, is not
made again. Removing touches only what this module created.
"""

from __future__ import annotations

import base64
import json
import os
import subprocess
import sys
from pathlib import Path

from ..agents.base import cli_command, server_launch
from ..files import write_text_atomic
from ..paths import HOME_ENVIRONMENT_VARIABLE, data_home, in_package_storage

LAUNCHER = "knowitall2-app.pyw"
ICON = "knowitall2.ico"
STATE_FILE = "app-shortcuts.json"
SHORTCUT_NAME = "KnowItAll2"
DESCRIPTION = "KnowItAll2: what your coding agents know and learn"
# Windows' ids for the folders the shortcuts go in: the Start menu's programs, and the desktop.
FOLDERID_PROGRAMS = "A77F5D77-2E2B-44C3-A6A2-ABA601054A51"
FOLDERID_DESKTOP = "B4BFCC3A-DB2C-424C-B029-7FE99A87C641"
# PowerShell ends a single-quoted string at any of these, unless it is doubled.
_SINGLE_QUOTES = ("'", "\u2018", "\u2019", "\u201a", "\u201b")
# The state of each place: "created", "pending" (the Start menu, waiting for the
# app's first run outside a package), or "removed" (by the user; never remade).
PLACES = ("start_menu", "desktop", "menu")


class ShortcutError(RuntimeError):
    """The shortcut could not be made; the message says what to do instead."""


def launcher_path() -> Path:
    return data_home() / LAUNCHER


def render_launcher() -> str:
    launch = server_launch()
    lines = ['"""Generated by KnowItAll2 setup: opens the KnowItAll2 app."""', "import os", "import sys", ""]
    if "PYTHONPATH" in launch.env:
        lines.append(f"sys.path.insert(0, {launch.env['PYTHONPATH']!r})")
    if HOME_ENVIRONMENT_VARIABLE in launch.env:
        lines.append(f"os.environ.setdefault({HOME_ENVIRONMENT_VARIABLE!r}, {launch.env[HOME_ENVIRONMENT_VARIABLE]!r})")
    lines += ["from knowitall2.app import run", "", "raise SystemExit(run())", ""]
    return "\n".join(lines)


def install(*, from_app: bool = False) -> list[str]:
    """Make the shortcut if it was never made; returns what changed.

    Setup calls this for every agent it sets up, so a second call changes
    nothing. The app calls it with ``from_app`` to finish a Start menu
    shortcut that setup could only put on the desktop.
    """

    state = load_state()
    if from_app:
        if sys.platform != "win32" or state.get("start_menu") != "pending":
            return []
        outcome = _place(_windows_shortcuts()[0])
        if outcome != "created":
            return []
        state["start_menu"] = "created"
        save_state(state)
        return ["added KnowItAll2 to the Start menu"]
    if state and all(value == "removed" for value in state.values()):
        return []
    changes = _refresh_launcher()
    if sys.platform != "win32":
        if state.get("menu") is None:
            changes.append(_create_linux(launcher_path()))
            state["menu"] = "created"
        save_state(state)
        return changes
    start_menu, desktop = _windows_shortcuts()
    if state.get("start_menu") in (None, "pending"):
        if _place(start_menu) == "created":
            state["start_menu"] = "created"
            changes.append(f"added KnowItAll2 to the Start menu ({start_menu})")
        else:
            state["start_menu"] = "pending"
    if state.get("start_menu") == "pending" and state.get("desktop") is None:
        _place(desktop)
        state["desktop"] = "created"
        changes.append(
            f"put a KnowItAll2 shortcut on the desktop ({desktop}); the app adds itself to the Start menu the first "
            "time it is opened from there"
        )
    save_state(state)
    return changes


def create(*, desktop: bool = False) -> list[str]:
    """Make the shortcut now, even if it was removed before; returns what was created."""

    changes = _refresh_launcher(always=True)
    state = load_state()
    if sys.platform != "win32":
        changes.append(_create_linux(launcher_path()))
        state["menu"] = "created"
        save_state(state)
        return changes
    start_menu, desktop_path = _windows_shortcuts()
    hidden = _place(start_menu) != "created"
    state["start_menu"] = "pending" if hidden else "created"
    if not hidden:
        changes.append(f"created the shortcut {start_menu}")
    if desktop:
        _place(desktop_path)
        state["desktop"] = "created"
        changes.append(f"created the shortcut {desktop_path}")
    save_state(state)
    if hidden:
        advice = (
            "This program runs inside a packaged Windows app, so Windows would hide a Start menu shortcut in that "
            "app's private storage. Open the app from the desktop shortcut, or run `knowitall2 app --shortcut` from "
            "your own terminal, to add it"
        )
        if not desktop:
            raise ShortcutError(advice + "; add --desktop for a desktop shortcut.")
        changes.append("did not add the Start menu shortcut yet: " + advice[0].lower() + advice[1:] + ".")
    return changes


def remove() -> list[str]:
    removed = []
    for path in [*_windows_shortcuts(), _linux_entry(), launcher_path(), data_home() / ICON]:
        if path is not None and path.is_file():
            path.unlink()
            removed.append(f"removed {path}")
    save_state({place: "removed" for place in PLACES})
    return removed


def load_state() -> dict[str, str]:
    try:
        data = json.loads((data_home() / STATE_FILE).read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return {}
    return {key: value for key, value in data.items() if key in PLACES and isinstance(value, str)} if isinstance(
        data, dict) else {}


def save_state(state: dict[str, str]) -> None:
    write_text_atomic(data_home() / STATE_FILE, json.dumps(state, indent=2) + "\n")


def describe() -> tuple[bool, str, str | None]:
    """For ``doctor``: whether the shortcut is in place, what it is, and how to fix it."""

    state = load_state()
    fix = f"Run: {cli_command('app', '--shortcut')}"
    if not launcher_path().is_file() and any(value == "created" for value in state.values()):
        return False, f"the shortcut's launcher {launcher_path()} is missing", fix
    if sys.platform != "win32":
        entry = _linux_entry()
        if state.get("menu") == "created" and entry is not None and entry.is_file():
            return True, f"in the applications menu ({entry})", None
    elif state.get("start_menu") == "created":
        return True, "in the Start menu", None
    elif state.get("start_menu") == "pending":
        if _windows_shortcuts()[1].is_file():
            return True, ("on the desktop; the app adds itself to the Start menu the first time it is opened "
                          "from there"), None
        return False, "not in the Start menu yet, and the desktop shortcut is gone", (
            f"Run `{cli_command('app', '--shortcut')}` from your own terminal (outside the Claude or Codex app)")
    if any(value == "removed" for value in state.values()):
        return True, "removed at your request", None
    return False, "not installed", fix


def _refresh_launcher(*, always: bool = False) -> list[str]:
    launcher = launcher_path()
    text = render_launcher()
    try:
        current = launcher.read_text(encoding="utf-8")
    except OSError:
        current = None
    if current == text and not always:
        return []
    write_text_atomic(launcher, text)
    return [] if current is not None else [f"wrote the app launcher {launcher}"]


def _windows_shortcuts() -> list[Path]:
    """Where the Start menu and desktop shortcuts go: Windows' own folders, which OneDrive may have moved."""

    if sys.platform != "win32":
        return []
    names = [_known_folder(FOLDERID_PROGRAMS), _known_folder(FOLDERID_DESKTOP)]
    if not all(names):
        folders = _powershell("[Environment]::GetFolderPath('Programs'); [Environment]::GetFolderPath('Desktop')")
        names = [line.strip() for line in folders.splitlines() if line.strip()]
    if len(names) != 2:
        names = [str(Path(os.environ.get("APPDATA", Path.home())) / "Microsoft" / "Windows" / "Start Menu" / "Programs"),
                 str(Path.home() / "Desktop")]
    return [Path(folder) / f"{SHORTCUT_NAME}.lnk" for folder in names]


def _place(path: Path) -> str:
    """Write one Windows shortcut: "created", or "hidden" when Windows would keep it in a package's storage."""

    icon = data_home() / ICON
    if not icon.is_file():
        from .icon import ico_bytes

        icon.write_bytes(ico_bytes())
    python = Path(sys.executable)
    windowless = python.with_name("pythonw.exe")
    target = windowless if windowless.is_file() else python
    path.parent.mkdir(parents=True, exist_ok=True)
    _write_lnk(path, target=target, arguments=f'"{launcher_path()}"', folder=data_home(), icon=icon)
    if not path.is_file():
        raise ShortcutError(f"Windows did not create {path}.")
    if in_package_storage(path):
        # Written from inside a packaged app, the file went to that app's private
        # storage, where the Start menu never looks.
        path.unlink(missing_ok=True)
        return "hidden"
    return "created"


def _known_folder(folder_id: str) -> str | None:
    """A Windows known folder, such as the desktop, as Windows itself has it; None when it cannot say."""

    import ctypes
    import uuid

    try:
        shell32, ole32 = ctypes.WinDLL("shell32"), ctypes.WinDLL("ole32")
        shell32.SHGetKnownFolderPath.argtypes = [ctypes.c_void_p, ctypes.c_uint32, ctypes.c_void_p,
                                                 ctypes.POINTER(ctypes.c_void_p)]
        shell32.SHGetKnownFolderPath.restype = ctypes.c_long
        ole32.CoTaskMemFree.argtypes = [ctypes.c_void_p]
        ole32.CoTaskMemFree.restype = None
        folder = ctypes.create_string_buffer(uuid.UUID(folder_id).bytes_le, 16)
        found = ctypes.c_void_p()
        result = shell32.SHGetKnownFolderPath(folder, 0, None, ctypes.byref(found))
        try:
            if result != 0 or not found.value:
                return None
            return ctypes.wstring_at(found.value) or None
        finally:
            ole32.CoTaskMemFree(found)
    except (OSError, AttributeError, ValueError):
        return None


def quoted(value: object) -> str:
    """``value`` as a PowerShell string, which also ends at a typographic single quote unless it is doubled."""

    text = str(value)
    for mark in _SINGLE_QUOTES:
        text = text.replace(mark, mark * 2)
    return "'" + text + "'"


def _write_lnk(path: Path, *, target: Path, arguments: str, folder: Path, icon: Path) -> None:
    script = "\n".join([
        "$shell = New-Object -ComObject WScript.Shell",
        f"$link = $shell.CreateShortcut({quoted(path)})",
        f"$link.TargetPath = {quoted(target)}",
        f"$link.Arguments = {quoted(arguments)}",
        f"$link.WorkingDirectory = {quoted(folder)}",
        f"$link.IconLocation = {quoted(str(icon) + ',0')}",
        f"$link.Description = {quoted(DESCRIPTION)}",
        "$link.Save()",
    ])
    _powershell(script, failure="Windows could not create the shortcut")


def _powershell(script: str, *, failure: str | None = None) -> str:
    """Run a short Windows PowerShell script, passed encoded so no path needs quoting on a command line.

    PowerShell writes what it prints in the console's code page, which has no
    "é" or "山", so it is told to write UTF-8 first.
    """

    script = "[Console]::OutputEncoding = New-Object System.Text.UTF8Encoding $false\n" + script
    encoded = base64.b64encode(script.encode("utf-16-le")).decode("ascii")
    try:
        completed = subprocess.run(
            ["powershell.exe", "-NoProfile", "-NonInteractive", "-ExecutionPolicy", "Bypass", "-EncodedCommand",
             encoded],
            capture_output=True, timeout=60, creationflags=subprocess.CREATE_NO_WINDOW,
        )
    except (OSError, subprocess.SubprocessError) as exc:
        if failure:
            raise ShortcutError(f"{failure}: {exc}") from exc
        return ""
    if completed.returncode != 0 and failure:
        detail = completed.stderr.decode("utf-8", errors="replace").strip().splitlines()[-1:] or ["no detail"]
        raise ShortcutError(f"{failure}: {detail[0]}")
    return completed.stdout.decode("utf-8", errors="replace")


def _linux_entry() -> Path | None:
    if sys.platform == "win32":
        return None
    base = Path(os.environ.get("XDG_DATA_HOME") or Path.home() / ".local" / "share")
    return base / "applications" / "knowitall2.desktop"


def _create_linux(launcher: Path) -> str:
    entry = _linux_entry()
    assert entry is not None
    icon = Path(__file__).resolve().parent / "static" / "icon.svg"
    write_text_atomic(entry, "\n".join([
        "[Desktop Entry]", "Type=Application", f"Name={SHORTCUT_NAME}", f"Comment={DESCRIPTION}",
        f"Exec={desktop_exec([sys.executable, str(launcher)])}", f"Icon={icon}", "Terminal=false",
        "Categories=Development;", "",
    ]))
    entry.chmod(0o755)
    return f"added KnowItAll2 to the applications menu ({entry})"


def desktop_exec(arguments: list[str]) -> str:
    """A menu entry's ``Exec=`` value that runs ``arguments`` whatever characters the paths hold.

    The Desktop Entry Specification quotes each argument and puts a backslash
    before each double quote, backtick, dollar sign and backslash in it; then
    every backslash is escaped once more (the rule for all values), and a
    percent sign is written twice.
    """

    quoted_arguments = []
    for argument in arguments:
        inside = "".join("\\" + character if character in '"`$\\' else character for character in argument)
        quoted_arguments.append('"' + inside.replace("\\", "\\\\").replace("%", "%%") + '"')
    return " ".join(quoted_arguments)
